import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "VictorMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "VictorMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "Regular"
